### ISSUE TITLE
Custom admin URL

### ISSUE THREAD

**Issue by mrnebbi** [owldesign/Form-Builder#2]
### Description

Plugin navigation (Dashboard, Forms, Entries, etc) doesn't respect custom admin url, and instead uses "admin/formbuilder...".

### Steps to reproduce

1. Install plugin
2. Try to access from form builder sidebar navigation

### Additional info

- Craft version: 2.6.2994
- Plugin version: 1.0.0
- PHP version: 5.6.30

**Comment by owldesign** [comment]
This one was important, thanks for submitting it. Fixed

**Comment by mrnebbi** [comment]
My pleasure! Happy to help. Thanks for making great plugins 👍
