### ISSUE TITLE
Plugin Settings error

### ISSUE THREAD

**Issue by mrnebbi** [owldesign/Form-Builder#3]
### Description

The settings panel tries to open using http://site/custom_admin/formBuilder/settings, resulting a `Variable "settings" does not exist.` error.

![screen shot 2017-11-06 at 14 54 40](https://user-images.githubusercontent.com/708691/32446982-87053ad0-c302-11e7-9065-ca4f71ca3f6e.png)

### Steps to reproduce

1. Install plugin
2. Go to Craft Settings
3. Click FormBuilder icon, or click Plugins and the settings icon for FormBuilder

### Additional info

- Craft version: 2.6.2994
- Plugin version: 1.0.0
- PHP version: 5.6.30

**Comment by owldesign** [comment]
fixed!
