### ISSUE TITLE
500 Error w/AJAX Submission

### ISSUE THREAD

**Issue by siebird** [owldesign/Form-Builder#4]
Just updated to the latest Craft and I'm having issues submitting w/AJAX. Getting a 500 error: `Internal Server Error Property "Craft\FormBuilder_EntryModel." is not defined.`

Any ideas on what could be causing this? Thanks!

I also tried w/o ajax and I'm getting the same error.

### Additional info

- Craft version: 2.6.3015
- Plugin version: 1.0.1
- PHP version: 7.1

**Comment by owldesign** [comment]
Was related to an error within email notifications plugin.
